# Generated by Django 2.2 on 2022-12-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
