# Generated by Django 4.1.6 on 2023-05-09 14:42

from django.db import migrations, models
import myauth.models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=myauth.models.profile_preview_directory_path,
            ),
        ),
    ]
