# Generated by Django 4.1.6 on 2023-05-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0011_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
