# Generated by Django 4.1.5 on 2023-01-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.SmallIntegerField(default=0),
        ),
    ]
