# Generated by Django 4.1.6 on 2023-12-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
