# Generated by Django 2.2 on 2023-01-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='news_id',
            new_name='news',
        ),
    ]
