# Generated by Django 2.2 on 2023-01-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_auto_20230108_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Флаг активности'),
        ),
    ]
