# Generated by Django 2.2 on 2023-01-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_auto_20230108_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(default='', max_length=1000, verbose_name='Содержание'),
        ),
    ]
